### ISSUE TITLE
Word list is not comprehensive?

### ISSUE THREAD

**Issue by venomoustoad** [jason-chao/wordle-solver#1]
nice job on the app. I tried the wordle_game.py , it could not find a couple of words that I tried (gloat and glean)- you might want to use a different dictionary ? Assume you are using the same dictionary for the solver too?

**Comment by jasonvmiller** [comment]
Both of these words are in the `english_words_alpha_dwyl.txt` file. If you're using the CLI, just type `!extended` to pull that (bigger, more complete) list instead.

**Comment by venomoustoad** [comment]
Ah I missed that in the readme, thanks
