### ISSUE TITLE
Flaw in logic?

### ISSUE THREAD

**Issue by venomoustoad** [jason-chao/wordle-solver#2]
I am unable to detect the exact flaw in the logic, but this scenario gives "Sorry, no other possible words.  Please check the result symbols you entered.
Please enter you last try as word:symbols" after the ORGAN guess.

The solution is RAGAS and all the words are in the English list files. I checked.
CLEAR:___+?
ORGAN: _?++_
SUGAR:?_++?
RAGAS:+++++

**Comment by jasonvmiller** [comment]
By default, the word-list loader ignores files ending in `s` that don't have two consecutive `s` at the end (like `guess`.) If you want to fix this, change the code:

```
self.word_list = Utility.load_word_list(self.word_list_file_path, word_length, True)
```

so that the last parameter is `False` (not `True`) so the word-list loader won't drop `RAGAS` from the list:

```
Please enter you last try as word:symbols
CLEAR:___+?
Suggested words (from simple word list):
        broad
        urban
        roman
        bryan
        brian
        array
        strap
        organ
        sarah
        spray
Please enter you last try as word:symbols
ORGAN:_?++_
Suggested words (from extended word list):
        ragas
```

**Comment by jason-chao** [comment]
@jasonvmiller  Thank you so much for pointing out the issue.  I assumed that the plural form of nouns would not be chosen as hidden words.   Frankly, the exclusion of plurals is crucial in improving performance.  I will see what would be the better way to exclude the plurals while not wrongly filtering out singular nouns ended with a single "s".   

I am sorry for the slow reply.  I have been busy working on a web-based UI for the solver, which will be out in the next 24 hours.  The web UI will expose the option of "including plurals" to the users.

**Comment by jasonvmiller** [comment]
@jason-chao tyvm for releasing this, it's wonderful and I enjoyed reading your solution!

**Comment by jason-chao** [comment]
@jasonvmiller  and @venomoustoad : please check the new web-based UI for the solver at [https://wordle-solver.jasontc.net/](https://wordle-solver.jasontc.net/).  This web UI provides the option to "include plurals" in the search for suggested words.   The issue with "RAGAS" case should be addressed when you check "include plurals". 

I will also update the CLI version in the repo to allow users to turn on the "include plurals" option.

**Comment by jason-chao** [comment]
You may now pass `--plurals True` in the arguments to [wordle_solver.py](https://github.com/jason-chao/wordle-solver/blob/main/wordle_solver.py) and [wordle_game.py](https://github.com/jason-chao/wordle-solver/blob/main/wordle_game.py) to prevent the exclusion of plurals from the word list.
