### ISSUE TITLE
word lists?

### ISSUE THREAD

**Issue by ghost** [jason-chao/wordle-solver#3]
Hi,

Just wondering if you would consider (optionally) using the word lists from wordle themselves?

12972 official valid 5-letter words taken from the Wordle website source https://www.powerlanguage.co.uk/wordle/main.c1506a22.js

2315 "common" guessable 5-letter words taken from the Wordle website source https://www.powerlanguage.co.uk/wordle/main.c1506a22.js

This would mean that only words the Wordle accepts would be suggested

**Comment by jason-chao** [comment]
@donotdox  Thank you so much for letting me the word lists from the original Wordle.  

I edited the README to show the position of the project.  This project is positioned to solve not only the original implementation of Wordle but also other/future implementations of the game.   Moreover, this project supports a variable word length.

Therefore, I do not plan to rely on the word lists extracted from the original implementation of Wordle.  But, in my head, I am thinking of making a variant of Wordle-Solver that mainly targets the original implementation.  In this case, I will definitely rely on the lists extracted from the original Wordle. 

By the way, if interested, please check [the web-UI](https://wordle-solver.jasontc.net/) that I just released.   You will see the option to change the number of letters.
