### ISSUE TITLE
Clarify 3.42 average moves to win?

### ISSUE THREAD

**Issue by fkodom** [jason-chao/wordle-solver#4]
Hi! I wanted to suggest that you clarify the "3.42 average tries" claim in your README. Judging from the benchmark files, that's based on a much smaller word set than the official Wordle game. Since all of the other benchmarks are higher, it seems like the true performance on Wordle would be noticeably higher than 3.42?

Thanks!

**Comment by jason-chao** [comment]
@fkodom  Thank you so much for noticing this.  I am sorry for the confusion caused.  I will add some clarification to README in a bit.  

This project is positioned as a solver for the Wordle game in general, now just the original implementation of Wordle but also other unofficial implementations.  Furthermore, a key feature of this solver is the support for variable word length.  So, it does not target the word list of the original Wordle.

The "3.42 tries on average" is based on MIT's 10k word list, which the [WordleGame](https://github.com/jason-chao/wordle-solver/blob/main/wordle_game.py) class uses by default.   The reason for using a shorter list is to make the game a lot more playable to people who struggle with vocabulary (like myself).

For your information, the performance of this solver when it targets the word list of the original Wordle is as follows.

```
9049 words - average: 4.631340479611007 tries
Guessing failed within 6 tries: 783 words
```

**Comment by fkodom** [comment]
Got it -- thanks for the clarification! It's a great web app, by the way. Haha much more convenient than other CLI-based solvers 😄
