### ISSUE TITLE
Needs not in word list

### ISSUE THREAD

**Issue by DaCuteRaccoon** [jason-chao/wordle-solver#6]
Add the word `needs` to the word list

**Comment by jason-chao** [comment]
This question has been answered in [https://github.com/jason-chao/wordle-solver/issues/2](https://github.com/jason-chao/wordle-solver/issues/2)

All plurals are not loaded into the solver by default.  The word `needs` is on the word lists though it is considered the plural form of the noun `need`. 

If you really want to include plurals in your search, please check the `include plurals` box in the web UI or pass `--plurals True` in the argument to the CLI.

**Comment by DaCuteRaccoon** [comment]
> This question has been answered in #2
> 
> All plurals are not loaded into the solver by default. The word `needs` is on the word lists though it is considered the plural form of the noun `need`.
> 
> If you really want to include plurals in your search, please check the `include plurals` box in the web UI or pass `--plurals True` in the argument to the CLI.

But I was using the web version of the solver, as I don't have python, so it doesn't work...
Maybe I'll fork it

**Comment by jason-chao** [comment]
@DaCuteRaccoon  In the web version, the `include plurals` checkbox is in the top right corner.   I hope it helps.
